### ISSUE TITLE
Cluster capacity was not limited by limitrange

### ISSUE THREAD

**Issue by chengzhang1016** [ingvagabund/cluster-capacity#11]
I found it doesn't base on limitrange while estimating cluster capacity. 
Problem Description: 
1. Shouldn't schedule any pod while limit/request value in pod yaml larger than Max of limitrange
2. Shouldn't schedule any pod while limit/request value in pod yaml smaller than Min of limitrange
3. Should use default limit/request of limitrange to schedule pods while limit/request value is empty in pod yaml

How to reproduce:
1. Create namespace "cluster-capacity"
```
# kc create namespace cluster-capacity
```

2. Create limitrange in namespace "cluster-capacity"
```
# cat limits.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: hpclimits
  namespace: cluster-capacity
spec:
  limits:
  - max:
      cpu: "400m"
      memory: 200Mi
    min:
      cpu: 20m
      memory: 12Mi
    type: Pod
  - default:
      cpu: 100m
      memory: 80Mi
    defaultRequest:
      cpu: 50m
      memory: 60Mi
    max:
      cpu: "200m"
      memory: 100Mi
    min:
      cpu: 10m
      memory: 6Mi
    type: Container
# kc create -f limits.yaml
```

3. Estimate cluster capacity with limit-pod1.yaml, the limit/request value in pod yaml larger than Max of limitrange.
```
# cat limit-pod1.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: cluster-capacity-stub-container
  namespace: cluster-capacity
spec:
  containers:
  - image: gcr.io/google_containers/pause:2.0
    imagePullPolicy: Always
    name: cluster-capacity-stub-container
    resources:
      limits:
        cpu: 800m
        memory: 600Mi
      requests:
        cpu: 700m
        memory: 500Mi
  dnsPolicy: Default
  restartPolicy: OnFailure
status: {}
# cc --podspec ./limit-pod1.yaml --verbose
```

Actual Result:
3. Still schedule base on limit/request in pod yaml file, but not consider limitation of limitrange.

Expect Result:
3. No instance of the pod can be scheduled.
