### ISSUE TITLE
Need to check namespace in `metadata.namespce` of pod yaml is exist or not before estimate and schedule pods

### ISSUE THREAD

**Issue by chengzhang1016** [ingvagabund/cluster-capacity#14]
I think we need to check namespace in `metadata.namespce` of pod yaml is exist or not before estimate and schedule pods.
In another word, user want to know how many pods can be scheduled in cluster, but no namespace `cluster-capacity` in current cluster.  Actually, below pod cannot be created as no namespace cluster-capacity.
```
apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  namespace: cluster-capacity
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
  - name: php-redis
    image: gcr.io/google-samples/gb-frontend:v4
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 100Mi
  restartPolicy: "OnFailure"
  dnsPolicy: "Default"
```
