### ISSUE TITLE
"restartPolicy" and "dnsPolicy" shouldn't be "Required value"

### ISSUE THREAD

**Issue by chengzhang1016** [ingvagabund/cluster-capacity#16]
"restartPolicy" and "dnsPolicy" shouldn't be "Required value". For example, estimate cluster capacity with below yaml (without "restartPolicy" and "dnsPolicy")
```
# cat simple-pod1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  namespace: cluster-capacity
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
  - name: php-redis
    image: gcr.io/google-samples/gb-frontend:v4
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 100Mi
```
```
# cc --podspec simple-pod1.yaml
Failed to parse pod spec file: Invalid pod: "Required value: spec.restartPolicy, Required value: spec.dnsPolicy"
```
