### ISSUE TITLE
"Pod requirements" in output should use resource request, and have duplicate info in output

### ISSUE THREAD

**Issue by chengzhang1016** [ingvagabund/cluster-capacity#6]
Problem 1: The "Pod requirements" in output is using the value of resource limit, but not resource request.
Problem 2: The output have duplicate info about "duplicate" while running with `--verbose`. Such as:
```
fit failure on node (ec2-54-165-2-61.compute-1.amazonaws.com): Insufficient cpu
fit failure on node (ec2-52-90-124-47.compute-1.amazonaws.com): Insufficient cpu
```
How to reproduce:
1. Create a yaml file without resource limit
```
# cat simple-pod3.yaml
apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  namespace: cluster-capacity
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
  - name: php-redis
    image: gcr.io/google-samples/gb-frontend:v4
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 150m
        memory: 100Mi
  restartPolicy: "OnFailure"
  dnsPolicy: "Default"
```
2. Estimate cluster capacity
```
# cc --podspec ./simple-pod3.yaml --verbose
E1128 21:52:55.638500   14226 factory.go:583] Error scheduling cluster-capacity small-pod-16: pod (small-pod-16) failed to fit in any node
fit failure on node (ec2-54-165-2-61.compute-1.amazonaws.com): Insufficient cpu
fit failure on node (ec2-52-90-124-47.compute-1.amazonaws.com): Insufficient cpu
; retrying
**Pod requirements:
	- cpu: 0
	- memory: 0**

The cluster can schedule 16 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-16) failed to fit in any node
fit failure on node (ec2-54-165-2-61.compute-1.amazonaws.com): Insufficient cpu
fit failure on node (ec2-52-90-124-47.compute-1.amazonaws.com): Insufficient cpu

Pod distribution among nodes:
	- ec2-54-165-2-61.compute-1.amazonaws.com: 7 instance(s)
	- ec2-52-90-124-47.compute-1.amazonaws.com: 9 instance(s)
```
